//! Translate a USB HID keyboard **usage ID** (what `flashdk-core::hid::KeyCode`
//! carries) into the **W3C `KeyboardEvent.code`** string kvmd expects (e.g. "KeyA").
//!
//! Both sides are public standards — USB HID Usage Tables (Usage Page 0x07) and the
//! W3C UI Events `code` values. We map between two open specs; no vendor source is
//! involved. Coverage here is the common subset; extend as needed.

/// Map a HID usage ID to kvmd's key name, or `None` if we haven't mapped it yet.
pub fn usage_to_code(usage: u8) -> Option<&'static str> {
    Some(match usage {
        // Letters (usage 0x04..=0x1D = A..Z)
        0x04 => "KeyA",
        0x05 => "KeyB",
        0x06 => "KeyC",
        0x07 => "KeyD",
        0x08 => "KeyE",
        0x09 => "KeyF",
        0x0A => "KeyG",
        0x0B => "KeyH",
        0x0C => "KeyI",
        0x0D => "KeyJ",
        0x0E => "KeyK",
        0x0F => "KeyL",
        0x10 => "KeyM",
        0x11 => "KeyN",
        0x12 => "KeyO",
        0x13 => "KeyP",
        0x14 => "KeyQ",
        0x15 => "KeyR",
        0x16 => "KeyS",
        0x17 => "KeyT",
        0x18 => "KeyU",
        0x19 => "KeyV",
        0x1A => "KeyW",
        0x1B => "KeyX",
        0x1C => "KeyY",
        0x1D => "KeyZ",
        // Number row (0x1E..=0x27 = 1..9,0)
        0x1E => "Digit1",
        0x1F => "Digit2",
        0x20 => "Digit3",
        0x21 => "Digit4",
        0x22 => "Digit5",
        0x23 => "Digit6",
        0x24 => "Digit7",
        0x25 => "Digit8",
        0x26 => "Digit9",
        0x27 => "Digit0",
        // Whitespace / control
        0x28 => "Enter",
        0x29 => "Escape",
        0x2A => "Backspace",
        0x2B => "Tab",
        0x2C => "Space",
        // Punctuation
        0x2D => "Minus",
        0x2E => "Equal",
        0x2F => "BracketLeft",
        0x30 => "BracketRight",
        0x31 => "Backslash",
        0x33 => "Semicolon",
        0x34 => "Quote",
        0x35 => "Backquote",
        0x36 => "Comma",
        0x37 => "Period",
        0x38 => "Slash",
        0x39 => "CapsLock",
        // Function keys
        0x3A => "F1",
        0x3B => "F2",
        0x3C => "F3",
        0x3D => "F4",
        0x3E => "F5",
        0x3F => "F6",
        0x40 => "F7",
        0x41 => "F8",
        0x42 => "F9",
        0x43 => "F10",
        0x44 => "F11",
        0x45 => "F12",
        // Navigation
        0x4A => "Home",
        0x4B => "PageUp",
        0x4C => "Delete",
        0x4D => "End",
        0x4E => "PageDown",
        0x4F => "ArrowRight",
        0x50 => "ArrowLeft",
        0x51 => "ArrowDown",
        0x52 => "ArrowUp",
        // Modifiers (usage 0xE0..=0xE7)
        0xE0 => "ControlLeft",
        0xE1 => "ShiftLeft",
        0xE2 => "AltLeft",
        0xE3 => "MetaLeft",
        0xE4 => "ControlRight",
        0xE5 => "ShiftRight",
        0xE6 => "AltRight",
        0xE7 => "MetaRight",
        _ => return None,
    })
}
